openapi: 3.0.0
info:
  title: Chess Cloud API
  description: API for our React-Nave mobile app
  version: 1.0.0
paths:
  /login:
    $ref: '../resources/login.yaml'
  /logout:
    $ref: '../resources/logout.yaml'
  /register:
    $ref: '../resources/register.yaml'
