name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create temp .env file
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.ENV_FILE }}" > src/main/resources/.env

      - name: Set up Amazon Corretto 21 JDK with Maven dependency caching
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Maven Package
        run: mvn --batch-mode --update-snapshots clean package

      - name: Upload JAR as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: chess-jar
          path: target/chess-cloud-1.0-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Add profile credentials to ~/.aws/credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile default
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile default
          aws configure set region ${{ secrets.AWS_REGION }} --profile default

      - name: Download JAR from build
        uses: actions/download-artifact@v4
        with:
          name: chess-jar
          path: target

      - name: List files in target directory
        run: ls -l target

      - name: Terraform fmt
        id: fmt
        run: |
          cd src/terraform
          terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
          cd src/terraform
          terraform init

      - name: Terraform Apply
        id: apply
        run: |
          cd src/terraform
          terraform apply -auto-approve

  integration-test:
    runs-on: ubuntu-latest
    needs:
      - deploy
      - build

    steps:
      - uses: actions/checkout@v4

      - name: Set up Amazon Corretto 21 JDK with Maven dependency caching
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Integration Test
        run: mvn --batch-mode failsafe:integration-test