name: Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create temp .env file
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.ENV_FILE }}" > src/main/resources/.env

      - name: Set up Amazon Corretto 21 JDK with Maven dependency caching
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests -DskipSwaggerCodegen -DskipSpotifyFormat

      - name: Run unit tests
        run: mvn test -DskipSwaggerCodegen -DskipSpotifyFormat
